# Generated by Django 5.2.3 on 2025-06-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0003_rename_simulations_simulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='labanswer',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='question',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='task',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='useranswer',
            field=models.CharField(max_length=500),
        ),
    ]
