# Generated by Django 5.2.3 on 2025-06-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0004_alter_simulation_labanswer_alter_simulation_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='labanswer',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='question',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='task',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='useranswer',
            field=models.TextField(max_length=500),
        ),
    ]
