# Generated by Django 5.2.3 on 2025-06-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0006_alter_simulation_labanswer_alter_simulation_question_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simulation',
            options={'ordering': ['box', 'date_created']},
        ),
        migrations.AlterField(
            model_name='simulation',
            name='task',
            field=models.TextField(max_length=600),
        ),
    ]
