# Generated by Django 5.2.3 on 2025-06-24 23:26

import django.core.validators
import simulations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0007_alter_simulation_options_alter_simulation_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for this simulation (JPG, PNG, GIF formats allowed)', null=True, upload_to=simulations.models.simulation_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='useranswer',
            field=models.TextField(blank=True, max_length=600),
        ),
    ]
