# Generated by Django 5.2.3 on 2025-06-25 01:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0008_simulation_image_alter_simulation_useranswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simulation',
            options={},
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='labanswer',
        ),
        migrations.AlterField(
            model_name='simulation',
            name='box',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='simulation_images/'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='question',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='task',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='useranswer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
