# Generated by Django 5.2.3 on 2025-06-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0009_alter_simulation_options_remove_simulation_labanswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='labanswer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
